name: adaptive_scrollbar
description: Adaptive desktop-style scrollbar that can be placed on either side of the screen.
version: 3.0.0
homepage: https://github.com/helpis-software/adaptive-scrollbar
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  hovering: ^1.0.4
  rxdart: ^0.27.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
